[package]
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
categories = ["game-development"]
description = "Procedural noise primitives for Bevy"
edition = "2021"
keywords = ["gamedev", "bevy", "noise", "pcg", "simplex_noise"]
license = "MIT"
name = "noisy_bevy"
repository = "https://github.com/johanhelsing/noisy_bevy"
version = "0.1.0"

[dependencies]
bevy = {version = "0.8", features = ["bevy_asset", "render"], default-features = false}

[dev-dependencies]
bevy = {version = "0.8", default-features = false, features = [
  "render",
  "bevy_asset",
  "bevy_winit",
  "filesystem_watcher",
  "x11", # github actions runners don't have libxkbcommon installed, so can't use wayland
]}
rand = "0.8"
bevy_egui = {version = "0.16", default-features = false, features = ["default_fonts"]}
bevy-inspector-egui = {version = "0.13", default-features = false}
bevy_pancam = { git = "https://github.com/johanhelsing/bevy_pancam", features = ["bevy-inspector-egui", "bevy_egui"] }
insta = "1.21"